version: "3.9"

services:
  db_container_1:
    image: postgres
    volumes:
      - ./data/db:/var/li/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  website_container_2:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangoProject:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db